### ISSUE TITLE
MVP(β版)レビュー依頼

### ISSUE THREAD

**Issue by nissy456789** [nissy456789/horror_comedy#54]
## 各種情報
サービスの概要とMVPで検証する事柄：
サービス概要：
怖いけどコメディ要素があるB級ホラー映画を紹介するCGMアプリです。
B級ホラー映画、ホラー映画自体を観たことがない人向けに映画紹介を目的としています。
ランキング機能によって人気な作品を調べる事ができ、レビューの投稿数によって報酬（称号アイテム）を受け取る事ができます。
観たい！ボタンを押すと作品をブックマークに登録します。その後、レコメンド機能によって同じカテゴリーの映画を紹介します。

MVPで検証する事柄：
- [ ] 新規登録
ログイン画面下部の「新規登録はこちら」から新規登録画面へ遷移する。
ユーザー名、メールアドレス、パスワード（６文字以上）を設定して登録ボタンを押すとログイン状態でトップ画面へ遷移する。
「パスワードを忘れた方はこちら」をクリックすると、パスワードを忘れた方(本リリースで実装予定です)と表示された仮ページへ遷移する。

- [ ] ログイン
新規登録時に登録したメールアドレスとパスワード（６文字以上）を使用してログインする。

- [ ] ログアウト
ログアウトボタンを押すだけでログイン状態から未ログイン状態になる。

- [ ] レビュー投稿
ログイン時：
フォームにレビューを入力して投稿ボタンを押すと右下に自分のユーザー名とレビュー内容が表示される。
未ログイン時：
レビューを入力して投稿ボタンを押すとログインページに遷移する。

- [ ] 作品一覧画面
トップページの「さぁ！まだ観ぬ世界へ！」ボタンとサイドバーの「作品一覧」ボタンを押すと作品一覧画面へ遷移する。
現在は３作品しかないので「ウィリーズワンダーランド」「ロンドンゾンビ紀行」「黄龍の村」がポスター画像として表示されている。

- [ ] 作品詳細画面
作品一覧画面の画像をクリックすると遷移する。
ポスター画像とタイトル、映画の説明が表示されている。
右上にレビュー投稿フォームがあり、右下には投稿されたレビューが表示されている。

サービス名：こみてらっ！
サービスURL：https://horror-comedy.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] ログイン
- [ ] ログアウト
- [ ] 新規登録
- [ ] レビュー投稿
- [ ] レビュー編集
- [ ] レビュー削除
- [ ] 作品一覧画面
- [ ] 作品詳細画面
- [ ] 検索機能

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください。

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください。なければこの項目は省略してください。
追加した機能：
- [ ] ログイン
- [ ] ログアウト
- [ ] 新規登録

MVPリリースでは実装しなかった機能
- [ ] レビュー編集
- [ ] レビュー削除
- [ ] 検索機能

## サービスイメージがわかるようなスクリーンショット等
![Image](https://github.com/user-attachments/assets/09b99840-9614-4333-bc6a-9c5d48578842)
![Image](https://github.com/user-attachments/assets/a3ec6000-cbe4-4958-8132-833ba760a3bd)

**Comment by TakenakaEri** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
